#use_frameworks!

platform :ios, '11.0'

target 'SLDevKit_Example' do
  pod 'SLDevKit', :path => '../'
  pod 'Aspects'
  pod 'YYCache'
#  pod 'NerdyUI'
  target 'SLDevKit_Tests' do
    inherit! :search_paths
    
    
  end
end
